<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BitMagic\BitMagic.Libraries\BitMagic.Common.Address\BitMagic.Common.Address.csproj" />
    <ProjectReference Include="..\..\BitMagic\BitMagic.X16Emulator\BitMagic.X16Emulator.Display\BitMagic.X16Emulator.Display.csproj" />
    <ProjectReference Include="..\..\BitMagic\BitMagic.X16Emulator\BitMagic.X16Emulator\BitMagic.X16Emulator.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="ANSI.Console" Version="2.5.0" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="EmulatorCore\EmulatorCore.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
